version: 2
project_name: pleno-dlp

builds:
  - id: pleno-dlp
    main: ./cmd/pleno-dlp
    binary: pleno-dlp
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

changelog:
  use: github
