// Package all blank-imports every concrete detector so that their init()
// functions run and register themselves with pkg/detectors. Per ADR-0002, the
// CLI binary blank-imports this package; new detectors add one line here.
package all

import (
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/airtable"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/algolia"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/anthropic"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/asana"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/atlassian"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/auth0"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/aws"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/azuread"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/bitbucketcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/brevo"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/buildkite"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/circleci"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/cloudflare"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/cohere"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/confluence"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/datadog"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/digitalocean"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/discord"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/doppler"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/dropbox"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/flyio"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gcp"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/generic"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/github"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gitlab"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/grafana"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/groq"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/heroku"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/hubspot"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/huggingface"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/intercom"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/jira"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/jwt"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/launchdarkly"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/linear"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mailchimp"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mailgun"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mistral"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mixpanel"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mongodbatlas"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/netlify"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/newrelic"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/notion"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/npm"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/okta"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/openai"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/openrouter"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pagerduty"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/paypal"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/piicc"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/piiemail"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/piiiban"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/piissn"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/plaid"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/postman"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/postmark"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/privatekey"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pypi"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/render"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/replicate"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/salesforcerefresh"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/segment"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/sendgrid"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/sentry"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/shodan"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/slack"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/snyk"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/spotify"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/square"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/stripe"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/telegram"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/terraformcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/together"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/twilio"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/vault"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/vercel"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/virustotal"
	// batch 6 — wire-stable order, never reorder.
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/awssession"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/azuresas"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/bitbucketserver"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/bugsnag"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/codecov"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/figma"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gcpapikey"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gcpoauth"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gitlabdeploy"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/honeycomb"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/klaviyo"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/rollbar"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/sumologic"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/tailscale"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/zoom"
	// batch 7 — wire-stable order, never reorder.
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/aliyun"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/azureapp"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/databricks"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/datadogapp"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/dopplercli"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/freshdesk"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gcpidtoken"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/hashicorpcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/launchdarklyrelay"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/ngrok"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/opsgenie"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/snowflake"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/tencentcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/terraformcloudteam"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/zendesk"
	// batch 8 — wire-stable order, never reorder. Connection-string and
	// URL-embedded credentials, container-registry tokens, AWS S3 / GCS
	// presigned URLs, Azure SQL connection strings, kubeconfig, Adobe.io.
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/adobeio"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/awss3presigned"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/azuresqlconn"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/basicauth"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/dockerhub"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gcssignedurl"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/ghcr"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/kafka"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/kubeconfig"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mongodb"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mysql"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/postgres"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/rabbitmq"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/redis"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/smtp"
	// batch 9 — wire-stable order, never reorder. Enterprise SaaS leverage
	// tokens (project-management, alt-cloud GPU/IaaS, edge-Redis, DB platform,
	// auth, BaaS service-role).
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/clerk"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/clickup"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gitter"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/launchnotes"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/linode"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/modal"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/monday"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/paperspace"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/planetscale"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/runpod"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/scaleway"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/supabase"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/trello"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/upstashredis"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/vultr"
	// batch 10 — wire-stable order, never reorder. Identity + IT-management
	// (OneLogin, JumpCloud), CI/CD (DroneCI, Harness), observability + cloud-
	// security (Lacework, Sysdig), localization (Lokalise), IaC platform
	// (Pulumi), docs/notes (Coda), email/comms (LoopsSo, Resend), mobile-app
	// platform (AppCenter), creator-platform OAuth (Twitch), secrets-manager
	// machine accounts (Bitwarden), and payments (Helcim).
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/appcenter"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/bitwarden"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/coda"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/droneci"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/harness"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/helcim"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/jumpcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/lacework"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/lokalise"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/loopsso"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/onelogin"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pulumi"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/resend"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/sysdig"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/twitch"
	// batch 11 — wire-stable order, never reorder. Frontier-model admin
	// keys (Anthropic Console), AI infra (Pinecone, Weaviate, VoyageAI,
	// Fireworks, Cerebras), GitHub Apps installation tokens, JFrog
	// Artifactory, Pendo, PostHog, Sentry user tokens, Cloudflare R2
	// access-key + secret pair, Mapbox secret tokens, Railway, Telnyx.
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/anthropicadmin"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/cerebras"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/cloudflarer2"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/fireworks"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/githubapp"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/jfrog"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mapbox"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pendo"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pinecone"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/posthog"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/railway"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/sentryuser"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/telnyx"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/voyageai"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/weaviate"
	// batch 12 — wire-stable order, never reorder. Observability +
	// log-aggregator tokens, uptime monitoring, error-tracking, incident /
	// status, and CI/CD bearer tokens. Self-hosted (AWX, ConcourseCI,
	// TeamCity) and per-customer-host SaaS (SplunkHEC, ElasticCloud) are
	// unverified-by-design because the host isn't in the chunk.
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/awx"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/concourseci"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/coralogix"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/elasticcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/honeybadger"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/loggly"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/logzio"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pagertree"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/pingdom"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/raygun"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/splunkhec"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/statuspage"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/teamcity"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/uptimerobot"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/victorops"
	// batch 13 — wire-stable order, never reorder. Modern DBaaS platforms,
	// CI/CD bearer tokens distinct from existing GitLab PAT/Deploy shapes,
	// email/marketing (Constant Contact), telephony (Vonage), and
	// enterprise integration platforms (Workato, Aikido).
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/aikidosecurity"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/aiven"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/argocd"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/clickhousecloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/cockroachcloud"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/constantcontact"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/fauna"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/gitlabpipeline"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/neon"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/spinnaker"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/tektonhub"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/tinybird"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/vonage"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/workato"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/yugabytecloud"
	// batch 14 — wire-stable order, never reorder. CDN/edge (Akamai,
	// Fastly), productivity / docs (Quip, Box, Zoho), payments / fintech
	// (Adyen, Wise, Razorpay, Mollie), telephony (MessageBird, Sinch),
	// S3-compatible object storage (Backblaze B2, Wasabi), identity
	// (Stytch), PaaS (Cloud66). Razorpay and Backblaze are paired
	// (key+secret); Stytch live, Razorpay live, and Mollie live surface
	// SeverityCritical when verified or matched.
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/adyen"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/akamai"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/backblazeb2"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/box"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/cloud66"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/fastly"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/messagebird"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/mollie"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/quip"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/razorpay"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/sinch"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/stytch"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/wasabi"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/wise"
	_ "github.com/plenoai/pleno-dlp/pkg/detectors/zoho"
)
