// Package cmd: `pleno-dlp hooks` installs a fast, offline agent/editor
// hook (issue #303). The hook itself is just this binary re-invoked as
// `pleno-dlp hooks run <target>` — install/uninstall only write a tiny
// wrapper script plus the target's own hook-registration file, and never
// duplicate scanning logic: every hook run shells out to the already
// tested `pleno-dlp scan stdin --no-verify` path (see scan.go), so hook
// behaviour never drifts from what an operator sees running that command
// by hand.
package cmd

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

const (
	hookTargetClaudeCode = "claude-code"
	hookTargetCursor     = "cursor"

	// hookScriptMarker is the substring every registered hook command
	// must contain, used to find (and only ever touch) our own entry
	// inside a settings/hooks file that may hold unrelated hooks too.
	hookScriptMarker = "pleno-dlp-scan.sh"
)

var hooksCmd = &cobra.Command{
	Use:   "hooks",
	Short: "Install, remove, or run a fast offline agent hook (pre-commit-style) backed by `scan stdin --no-verify`",
	Long: "Manage a latency-tolerant secret-scanning hook for AI coding agents.\n\n" +
		"`pleno-dlp hooks install claude-code|cursor` wires up the target's own hook\n" +
		"mechanism to call `pleno-dlp scan stdin --no-verify` — the network Verify()\n" +
		"round-trip is skipped so the hook stays fast enough to run on every edit or\n" +
		"commit. Findings are still reported (as unverified, never provider-confirmed)\n" +
		"so the hook trades confidence for latency; it is not a substitute for CI's\n" +
		"fully-verified `pleno-dlp scan` gate.\n\n" +
		"`pleno-dlp hooks run <target>` is internal plumbing invoked by the installed\n" +
		"hook config — it is not meant to be run directly.",
}

var hooksInstallCmd = &cobra.Command{
	Use:   "install <claude-code|cursor>",
	Short: "Install the hook for claude-code or cursor in the current project",
	Args:  cobra.ExactArgs(1),
	RunE:  runHooksInstall,
}

var hooksUninstallCmd = &cobra.Command{
	Use:   "uninstall <claude-code|cursor>",
	Short: "Remove a previously installed hook",
	Args:  cobra.ExactArgs(1),
	RunE:  runHooksUninstall,
}

var hooksRunCmd = &cobra.Command{
	Use:    "run <claude-code|cursor>",
	Short:  "Internal: translate one hook invocation into a scan stdin --no-verify call",
	Args:   cobra.ExactArgs(1),
	Hidden: true,
	RunE:   runHooksRun,
}

func init() {
	hooksCmd.AddCommand(hooksInstallCmd, hooksUninstallCmd, hooksRunCmd)
	Root.AddCommand(hooksCmd)
}

func runHooksInstall(cmd *cobra.Command, args []string) error {
	switch args[0] {
	case hookTargetClaudeCode:
		return installClaudeCodeHook(cmd)
	case hookTargetCursor:
		return installCursorHook(cmd)
	default:
		return fmt.Errorf("hooks install: unknown target %q (want %q or %q)", args[0], hookTargetClaudeCode, hookTargetCursor)
	}
}

func runHooksUninstall(cmd *cobra.Command, args []string) error {
	switch args[0] {
	case hookTargetClaudeCode:
		return uninstallClaudeCodeHook(cmd)
	case hookTargetCursor:
		return uninstallCursorHook(cmd)
	default:
		return fmt.Errorf("hooks uninstall: unknown target %q (want %q or %q)", args[0], hookTargetClaudeCode, hookTargetCursor)
	}
}

func runHooksRun(cmd *cobra.Command, args []string) error {
	switch args[0] {
	case hookTargetClaudeCode:
		return runHookClaudeCode(cmd)
	case hookTargetCursor:
		return runHookCursor(cmd)
	default:
		return fmt.Errorf("hooks run: unknown target %q (want %q or %q)", args[0], hookTargetClaudeCode, hookTargetCursor)
	}
}

// ---------------------------------------------------------------------
// Shared plumbing
// ---------------------------------------------------------------------

// hookScriptTemplate is the wrapper every installed hook actually
// executes. Both targets get a real script file (rather than an inline
// "binary + args" command string) because Cursor's hooks.json documents
// script-file entries but is not documented to split an argv the way a
// shell would — a generated script sidesteps that ambiguity for both
// targets uniformly.
const hookScriptTemplate = `#!/bin/sh
# Generated by ` + "`pleno-dlp hooks install %s`" + `. Do not edit by hand —
# re-run that command after upgrading or moving pleno-dlp to refresh the
# embedded binary path below.
exec %q hooks run %s
`

// writeHookScript (re)writes the wrapper script at relPath (relative to
// the current working directory) and returns relPath. Always overwrites:
// the script has no user-editable content, and reinstalling after an
// upgrade should always pick up the current binary path.
func writeHookScript(relPath, target string) (string, error) {
	exe := resolveExecutable()
	if exe == "" {
		return "", fmt.Errorf("hooks install: could not resolve pleno-dlp's own executable path")
	}
	if dir := filepath.Dir(relPath); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", fmt.Errorf("create %s: %w", dir, err)
		}
	}
	script := fmt.Sprintf(hookScriptTemplate, target, exe, target)
	if err := os.WriteFile(relPath, []byte(script), 0o755); err != nil {
		return "", fmt.Errorf("write %s: %w", relPath, err)
	}
	return relPath, nil
}

// removeHookScript deletes the wrapper script, tolerating "already gone".
func removeHookScript(relPath string) error {
	if err := os.Remove(relPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", relPath, err)
	}
	return nil
}

// loadJSONObject reads path as a top-level JSON object, preserving every
// key it doesn't understand as raw bytes so install/uninstall never
// clobbers unrelated settings. A missing or empty file yields an empty
// object rather than an error — first install has nothing to merge into.
func loadJSONObject(path string) (map[string]json.RawMessage, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]json.RawMessage{}, nil
		}
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if len(bytes.TrimSpace(data)) == 0 {
		return map[string]json.RawMessage{}, nil
	}
	obj := map[string]json.RawMessage{}
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, fmt.Errorf("parse %s (not a JSON object): %w", path, err)
	}
	return obj, nil
}

func writeJSONObject(path string, obj map[string]json.RawMessage) error {
	data, err := json.MarshalIndent(obj, "", "  ")
	if err != nil {
		return fmt.Errorf("encode %s: %w", path, err)
	}
	data = append(data, '\n')
	if dir := filepath.Dir(path); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// scanOfflineFunc is the seam runHookClaudeCode / runHookCursor call
// through instead of scanOffline directly. Production leaves it at the
// default; tests replace it with a fake so the allow/deny decision logic
// is verifiable without spawning a real pleno-dlp subprocess (mirrors the
// uvBin/gitBin override pattern in pii_server.go).
var scanOfflineFunc = scanOffline

// scanOffline shells out to this same pleno-dlp binary (`scan stdin
// --no-verify`) against data and reports how many findings it emitted.
// Deliberately does not reimplement engine wiring: reusing the CLI path
// means hook behaviour — dedup, allowlist discovery, output shape —
// never drifts from `pleno-dlp scan stdin --no-verify` run by hand.
func scanOffline(data []byte) (int, error) {
	exe := resolveExecutable()
	if exe == "" {
		return 0, fmt.Errorf("could not resolve pleno-dlp's own executable path")
	}
	c := exec.Command(exe, "scan", "stdin", "--no-verify", "--quiet", "--format", "json")
	c.Stdin = bytes.NewReader(data)
	var stdout, stderr bytes.Buffer
	c.Stdout = &stdout
	c.Stderr = &stderr
	runErr := c.Run()
	if runErr != nil {
		var exitErr *exec.ExitError
		if !errors.As(runErr, &exitErr) {
			return 0, fmt.Errorf("run scan stdin: %w", runErr)
		}
		// Stdin scans always exit 0 — findings are reported on stdout,
		// never via the exit code (that gating is reserved for
		// file/git/SaaS kinds). Any non-zero exit is a real error.
		return 0, fmt.Errorf("scan stdin exited %d: %s", exitErr.ExitCode(), stderr.String())
	}
	if len(bytes.TrimSpace(stdout.Bytes())) == 0 {
		return 0, nil
	}
	var records []json.RawMessage
	if err := json.Unmarshal(stdout.Bytes(), &records); err != nil {
		return 0, fmt.Errorf("parse scan stdin output: %w", err)
	}
	return len(records), nil
}

// ---------------------------------------------------------------------
// claude-code: PreToolUse hook on Edit|Write in .claude/settings.json
// ---------------------------------------------------------------------

const (
	claudeScriptPath   = ".claude/hooks/pleno-dlp-scan.sh"
	claudeSettingsPath = ".claude/settings.json"
	claudeHookCommand  = "${CLAUDE_PROJECT_DIR}/" + claudeScriptPath
)

type claudeHookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

type claudeMatcher struct {
	Matcher string            `json:"matcher,omitempty"`
	Hooks   []claudeHookEntry `json:"hooks"`
}

func installClaudeCodeHook(cmd *cobra.Command) error {
	if _, err := writeHookScript(claudeScriptPath, hookTargetClaudeCode); err != nil {
		return err
	}

	root, err := loadJSONObject(claudeSettingsPath)
	if err != nil {
		return err
	}
	hooksObj := map[string]json.RawMessage{}
	if raw, ok := root["hooks"]; ok {
		if err := json.Unmarshal(raw, &hooksObj); err != nil {
			return fmt.Errorf("parse %s: key \"hooks\": %w", claudeSettingsPath, err)
		}
	}
	var preToolUse []claudeMatcher
	if raw, ok := hooksObj["PreToolUse"]; ok {
		if err := json.Unmarshal(raw, &preToolUse); err != nil {
			return fmt.Errorf("parse %s: key \"hooks.PreToolUse\": %w", claudeSettingsPath, err)
		}
	}

	state := "installed"
	found := false
	for mi := range preToolUse {
		for hi := range preToolUse[mi].Hooks {
			if !strings.Contains(preToolUse[mi].Hooks[hi].Command, hookScriptMarker) {
				continue
			}
			found = true
			if preToolUse[mi].Hooks[hi].Command != claudeHookCommand {
				preToolUse[mi].Hooks[hi].Command = claudeHookCommand
				state = "updated"
			}
		}
	}
	if !found {
		preToolUse = append(preToolUse, claudeMatcher{
			Matcher: "Edit|Write",
			Hooks:   []claudeHookEntry{{Type: "command", Command: claudeHookCommand}},
		})
	} else if state != "updated" {
		state = "unchanged"
	}

	if state == "unchanged" {
		fmt.Fprintf(cmd.OutOrStdout(), "claude-code hook already installed in %s (PreToolUse Edit|Write -> %s)\n", claudeSettingsPath, claudeHookCommand)
		return nil
	}

	raw, err := json.Marshal(preToolUse)
	if err != nil {
		return err
	}
	hooksObj["PreToolUse"] = raw
	hooksRaw, err := json.Marshal(hooksObj)
	if err != nil {
		return err
	}
	root["hooks"] = hooksRaw
	if err := writeJSONObject(claudeSettingsPath, root); err != nil {
		return err
	}

	fmt.Fprintf(cmd.OutOrStdout(), "%s claude-code hook:\n  script:   %s\n  settings: %s\n  trigger:  PreToolUse Edit|Write -> %s\n",
		map[string]string{"installed": "installed", "updated": "updated"}[state], claudeScriptPath, claudeSettingsPath, claudeHookCommand)
	return nil
}

func uninstallClaudeCodeHook(cmd *cobra.Command) error {
	root, err := loadJSONObject(claudeSettingsPath)
	if err != nil {
		return err
	}
	hooksObj := map[string]json.RawMessage{}
	if raw, ok := root["hooks"]; ok {
		if err := json.Unmarshal(raw, &hooksObj); err != nil {
			return fmt.Errorf("parse %s: key \"hooks\": %w", claudeSettingsPath, err)
		}
	}
	var preToolUse []claudeMatcher
	if raw, ok := hooksObj["PreToolUse"]; ok {
		if err := json.Unmarshal(raw, &preToolUse); err != nil {
			return fmt.Errorf("parse %s: key \"hooks.PreToolUse\": %w", claudeSettingsPath, err)
		}
	}

	removed := false
	kept := make([]claudeMatcher, 0, len(preToolUse))
	for _, m := range preToolUse {
		keptHooks := make([]claudeHookEntry, 0, len(m.Hooks))
		for _, h := range m.Hooks {
			if strings.Contains(h.Command, hookScriptMarker) {
				removed = true
				continue
			}
			keptHooks = append(keptHooks, h)
		}
		if len(keptHooks) > 0 {
			m.Hooks = keptHooks
			kept = append(kept, m)
		}
	}

	if !removed {
		fmt.Fprintf(cmd.OutOrStdout(), "claude-code hook not installed in %s; nothing to do\n", claudeSettingsPath)
		return nil
	}

	if len(kept) > 0 {
		raw, err := json.Marshal(kept)
		if err != nil {
			return err
		}
		hooksObj["PreToolUse"] = raw
	} else {
		delete(hooksObj, "PreToolUse")
	}
	if len(hooksObj) > 0 {
		hooksRaw, err := json.Marshal(hooksObj)
		if err != nil {
			return err
		}
		root["hooks"] = hooksRaw
	} else {
		delete(root, "hooks")
	}
	if err := writeJSONObject(claudeSettingsPath, root); err != nil {
		return err
	}
	if err := removeHookScript(claudeScriptPath); err != nil {
		return err
	}

	fmt.Fprintf(cmd.OutOrStdout(), "uninstalled claude-code hook: removed PreToolUse entry from %s and deleted %s\n", claudeSettingsPath, claudeScriptPath)
	return nil
}

// claudeHookPayload is the subset of Claude Code's PreToolUse stdin JSON
// this hook needs. The field that carries the content about to be written
// depends on the tool: Write uses tool_input.content (the whole new file),
// Edit uses tool_input.new_string (the replacement text), and MultiEdit
// uses tool_input.edits[].new_string (one replacement per edit). Reading
// only `content` silently let every Edit/MultiEdit through unscanned, so
// scanClaudeContent below concatenates all three.
type claudeHookPayload struct {
	ToolInput struct {
		FilePath  string `json:"file_path"`
		Content   string `json:"content"`
		NewString string `json:"new_string"`
		Edits     []struct {
			NewString string `json:"new_string"`
		} `json:"edits"`
	} `json:"tool_input"`
}

// scanClaudeContent returns every piece of about-to-be-written text carried
// by a PreToolUse payload, joined by newlines. Write populates Content;
// Edit populates NewString; MultiEdit populates Edits. A tool call may set
// more than one (or none), so all are collected rather than switched on
// tool_name — the hook scans whatever content is present regardless of
// which tool produced it.
func (p claudeHookPayload) scanClaudeContent() string {
	parts := make([]string, 0, 2+len(p.ToolInput.Edits))
	if p.ToolInput.Content != "" {
		parts = append(parts, p.ToolInput.Content)
	}
	if p.ToolInput.NewString != "" {
		parts = append(parts, p.ToolInput.NewString)
	}
	for _, e := range p.ToolInput.Edits {
		if e.NewString != "" {
			parts = append(parts, e.NewString)
		}
	}
	return strings.Join(parts, "\n")
}

// runHookClaudeCode implements the claude-code half of the PreToolUse
// contract: exit 0 (return nil) allows the Edit/Write, a non-nil error
// exits 2 (see main.go) which Claude Code treats as "block", surfacing
// stderr as the reason. Anything that isn't a genuine "secrets found"
// verdict fails open (allows, with a stderr warning) — a parsing or
// spawn failure in our own plumbing should never be able to wedge every
// edit the agent makes.
func runHookClaudeCode(cmd *cobra.Command) error {
	raw, err := io.ReadAll(cmd.InOrStdin())
	if err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "hooks run claude-code: read hook payload: %v — allowing\n", err)
		return nil
	}
	var payload claudeHookPayload
	if err := json.Unmarshal(raw, &payload); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "hooks run claude-code: parse hook payload: %v — allowing\n", err)
		return nil
	}
	content := payload.scanClaudeContent()
	if strings.TrimSpace(content) == "" {
		return nil
	}

	n, err := scanOfflineFunc([]byte(content))
	if err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "hooks run claude-code: %v — allowing\n", err)
		return nil
	}
	if n == 0 {
		return nil
	}
	target := payload.ToolInput.FilePath
	if target == "" {
		target = "(unknown file)"
	}
	return fmt.Errorf("pleno-dlp: %d potential secret(s) found in %s (offline, unverified scan) — rerun `pleno-dlp scan stdin` for full verification, or fix the finding before retrying", n, target)
}

// ---------------------------------------------------------------------
// cursor: beforeShellExecution hook gating `git commit` in .cursor/hooks.json
// ---------------------------------------------------------------------
//
// Cursor's afterFileEdit hook (the direct analogue of claude-code's
// PreToolUse Edit|Write) is documented as observation-only — it cannot
// deny or otherwise block the edit. beforeShellExecution is one of the
// three Cursor hook events that can actually return a permission
// decision, so instead this hook intercepts `git commit` invocations and
// scans the staged diff, which is a closer analogue to a pre-commit hook
// than to an edit-time hook anyway.

const (
	cursorScriptPath  = ".cursor/hooks/pleno-dlp-scan.sh"
	cursorHooksPath   = ".cursor/hooks.json"
	cursorHookEvent   = "beforeShellExecution"
	cursorHookCommand = "hooks/pleno-dlp-scan.sh" // relative to cursorHooksPath's directory
)

type cursorHookEntry struct {
	Command string `json:"command"`
}

func installCursorHook(cmd *cobra.Command) error {
	if _, err := writeHookScript(cursorScriptPath, hookTargetCursor); err != nil {
		return err
	}

	root, err := loadJSONObject(cursorHooksPath)
	if err != nil {
		return err
	}
	hooksObj := map[string]json.RawMessage{}
	if raw, ok := root["hooks"]; ok {
		if err := json.Unmarshal(raw, &hooksObj); err != nil {
			return fmt.Errorf("parse %s: key \"hooks\": %w", cursorHooksPath, err)
		}
	}
	var entries []cursorHookEntry
	if raw, ok := hooksObj[cursorHookEvent]; ok {
		if err := json.Unmarshal(raw, &entries); err != nil {
			return fmt.Errorf("parse %s: key \"hooks.%s\": %w", cursorHooksPath, cursorHookEvent, err)
		}
	}

	state := "installed"
	found := false
	for i := range entries {
		if !strings.Contains(entries[i].Command, hookScriptMarker) {
			continue
		}
		found = true
		if entries[i].Command != cursorHookCommand {
			entries[i].Command = cursorHookCommand
			state = "updated"
		}
	}
	if !found {
		entries = append(entries, cursorHookEntry{Command: cursorHookCommand})
	} else if state != "updated" {
		state = "unchanged"
	}

	if state == "unchanged" {
		fmt.Fprintf(cmd.OutOrStdout(), "cursor hook already installed in %s (%s -> %s)\n", cursorHooksPath, cursorHookEvent, cursorHookCommand)
		return nil
	}

	raw, err := json.Marshal(entries)
	if err != nil {
		return err
	}
	hooksObj[cursorHookEvent] = raw
	hooksRaw, err := json.Marshal(hooksObj)
	if err != nil {
		return err
	}
	root["hooks"] = hooksRaw
	root["version"] = json.RawMessage("1")
	if err := writeJSONObject(cursorHooksPath, root); err != nil {
		return err
	}

	fmt.Fprintf(cmd.OutOrStdout(), "%s cursor hook:\n  script: %s\n  config: %s\n  trigger: %s (gates `git commit`) -> %s\n",
		state, cursorScriptPath, cursorHooksPath, cursorHookEvent, cursorHookCommand)
	return nil
}

func uninstallCursorHook(cmd *cobra.Command) error {
	root, err := loadJSONObject(cursorHooksPath)
	if err != nil {
		return err
	}
	hooksObj := map[string]json.RawMessage{}
	if raw, ok := root["hooks"]; ok {
		if err := json.Unmarshal(raw, &hooksObj); err != nil {
			return fmt.Errorf("parse %s: key \"hooks\": %w", cursorHooksPath, err)
		}
	}
	var entries []cursorHookEntry
	if raw, ok := hooksObj[cursorHookEvent]; ok {
		if err := json.Unmarshal(raw, &entries); err != nil {
			return fmt.Errorf("parse %s: key \"hooks.%s\": %w", cursorHooksPath, cursorHookEvent, err)
		}
	}

	removed := false
	kept := make([]cursorHookEntry, 0, len(entries))
	for _, e := range entries {
		if strings.Contains(e.Command, hookScriptMarker) {
			removed = true
			continue
		}
		kept = append(kept, e)
	}

	if !removed {
		fmt.Fprintf(cmd.OutOrStdout(), "cursor hook not installed in %s; nothing to do\n", cursorHooksPath)
		return nil
	}

	if len(kept) > 0 {
		raw, err := json.Marshal(kept)
		if err != nil {
			return err
		}
		hooksObj[cursorHookEvent] = raw
	} else {
		delete(hooksObj, cursorHookEvent)
	}
	if len(hooksObj) > 0 {
		hooksRaw, err := json.Marshal(hooksObj)
		if err != nil {
			return err
		}
		root["hooks"] = hooksRaw
	} else {
		delete(root, "hooks")
	}
	if err := writeJSONObject(cursorHooksPath, root); err != nil {
		return err
	}
	if err := removeHookScript(cursorScriptPath); err != nil {
		return err
	}

	fmt.Fprintf(cmd.OutOrStdout(), "uninstalled cursor hook: removed %s entry from %s and deleted %s\n", cursorHookEvent, cursorHooksPath, cursorScriptPath)
	return nil
}

type cursorHookPayload struct {
	Command string `json:"command"`
	Cwd     string `json:"cwd"`
}

type cursorPermissionOutput struct {
	Permission   string `json:"permission"`
	UserMessage  string `json:"userMessage,omitempty"`
	AgentMessage string `json:"agentMessage,omitempty"`
}

// gitRe / commitRe together gate which shell commands pay the scan cost.
// Matching "git" and "commit" as separate whole words (rather than one
// anchored `git\s+commit` pattern) deliberately over-matches unusual
// invocations like `git -C repo commit` or `git commit --amend` at the
// cost of also firing on rarer non-commit commands that happen to
// mention both words — for a hook whose job is to gate commits, a false
// extra (fast, offline) scan is a much cheaper mistake than a missed one.
var (
	gitRe    = regexp.MustCompile(`\bgit\b`)
	commitRe = regexp.MustCompile(`\bcommit\b`)
)

// runHookCursor implements the cursor half of the beforeShellExecution
// contract: unlike claude-code, Cursor's permission decision travels as
// JSON on stdout (the `permission` field), not the process exit code, so
// this always exits 0 and prints either an allow or deny decision. Any
// internal failure (bad payload, git not found, scan spawn failure) fails
// open — allow, with a stderr warning — for the same reason as the
// claude-code path: our own plumbing breaking must never block every
// shell command the agent runs.
func runHookCursor(cmd *cobra.Command) error {
	raw, err := io.ReadAll(cmd.InOrStdin())
	if err != nil {
		return allowCursor(cmd, fmt.Sprintf("read hook payload: %v", err))
	}
	var payload cursorHookPayload
	if err := json.Unmarshal(raw, &payload); err != nil {
		return allowCursor(cmd, fmt.Sprintf("parse hook payload: %v", err))
	}
	if !gitRe.MatchString(payload.Command) || !commitRe.MatchString(payload.Command) {
		return allowCursor(cmd, "")
	}

	diff, err := gitDiffCached(payload.Cwd)
	if err != nil {
		return allowCursor(cmd, fmt.Sprintf("collect staged diff: %v", err))
	}
	if len(bytes.TrimSpace(diff)) == 0 {
		return allowCursor(cmd, "")
	}

	n, err := scanOfflineFunc(diff)
	if err != nil {
		return allowCursor(cmd, fmt.Sprintf("scan staged diff: %v", err))
	}
	if n == 0 {
		return allowCursor(cmd, "")
	}

	msg := fmt.Sprintf("pleno-dlp found %d potential secret(s) in the staged diff (offline, unverified scan). "+
		"Run `pleno-dlp scan git --repo .` or `pleno-dlp scan stdin` for full verification before committing.", n)
	return writeCursorPermission(cmd, cursorPermissionOutput{Permission: "deny", UserMessage: msg, AgentMessage: msg})
}

func allowCursor(cmd *cobra.Command, warnMsg string) error {
	if warnMsg != "" {
		fmt.Fprintf(cmd.ErrOrStderr(), "hooks run cursor: %s — allowing\n", warnMsg)
	}
	return writeCursorPermission(cmd, cursorPermissionOutput{Permission: "allow"})
}

func writeCursorPermission(cmd *cobra.Command, out cursorPermissionOutput) error {
	enc, err := json.Marshal(out)
	if err != nil {
		return err
	}
	fmt.Fprintln(cmd.OutOrStdout(), string(enc))
	return nil
}

func gitDiffCached(cwd string) ([]byte, error) {
	c := exec.Command("git", "diff", "--cached")
	if cwd != "" {
		c.Dir = cwd
	}
	var stdout, stderr bytes.Buffer
	c.Stdout = &stdout
	c.Stderr = &stderr
	if err := c.Run(); err != nil {
		return nil, fmt.Errorf("git diff --cached: %w: %s", err, stderr.String())
	}
	return stdout.Bytes(), nil
}
