package engine

import (
	"bytes"
	"regexp"
	"sync"
)

// IsPlaceholder reports whether raw is one of the well-known throwaway
// strings that show up in documentation, fixtures, and onboarding
// snippets — values no one ever provisions as a real credential. We
// reject them at the engine sink layer rather than per-detector because
// the same set of placeholders appears across every provider (AWS docs
// use AKIAIOSFODNN7EXAMPLE, Stripe docs use sk_test_…, Slack docs use
// xoxb-YOUR-TOKEN-HERE) — coding the list in one place beats sprinkling
// it across 600+ detectors.
//
// Match strategy:
//
//   - Substring (case-insensitive). Trips on any token that embeds an
//     obvious placeholder marker — covers AWS's AKIAIOSFODNN7EXAMPLE
//     via the EXAMPLE suffix, every flavour of YOUR_TOKEN /
//     YOUR_SECRET / YOUR_KEY, <TOKEN> bracket-style placeholders,
//     PLACEHOLDER, and REDACTED.
//   - Long runs. 8+ consecutive `X` or `x`, 10+ consecutive `0`.
//     Caught by precompiled regex so the match cost is one walk over
//     the raw bytes regardless of how many runs are tried.
//   - Exact match (case-insensitive). A short list of single-word
//     placeholders that are too generic to use as substrings —
//     `test` as substring would gut every real token containing the
//     three letters t-e-s-t. Exact-only here means "dummy" is rejected
//     but "dummynet" sails through.
//
// Returned value is true when the raw should be rejected. The bool is
// kept simple — no reason field — because placeholderSink doesn't
// surface per-finding rationale; it just reports a total count.
func IsPlaceholder(raw []byte) bool {
	if len(raw) == 0 {
		return false
	}
	// Lower-cased once; every substring check below reuses it. Avoids
	// allocating a new copy per pattern in the substring list.
	lower := bytes.ToLower(raw)
	for _, marker := range placeholderSubstrings {
		if bytes.Contains(lower, marker) {
			return true
		}
	}
	if placeholderRunsRE.Match(raw) {
		return true
	}
	for _, exact := range placeholderExactMatches {
		if bytes.Equal(lower, exact) {
			return true
		}
	}
	return false
}

// placeholderSubstrings are case-insensitive substring markers. Stored
// as lower-case []byte so the IsPlaceholder hot path is one ToLower +
// N bytes.Contains calls — no string conversions, no per-call allocs.
//
// Each entry earns its place by appearing in vendor documentation, in
// boilerplate generated by the major API client SDKs, or in committed
// fixtures across the trufflehog corpus we ported from.
var placeholderSubstrings = [][]byte{
	[]byte("example"),     // AWS AKIAIOSFODNN7EXAMPLE and dozens of others
	[]byte("your_token"),  // bare YOUR_TOKEN / YOUR_TOKEN_HERE
	[]byte("your_key"),    // bare YOUR_KEY / YOUR_API_KEY
	[]byte("your_secret"), // bare YOUR_SECRET
	[]byte("placeholder"),
	[]byte("redacted"),
	[]byte("<token>"),
	[]byte("<secret>"),
	[]byte("<key>"),
}

// placeholderRunsRE matches the two long-run patterns: 8+ consecutive
// X (any case) or 10+ consecutive 0. Combined into one regex so we
// walk the raw bytes once rather than twice. The thresholds match the
// shapes documented in the task (XXXXXXXX / 0000000000) and avoid the
// risk of tripping on shorter occurrences in legitimate base64 / hex
// tokens that happen to contain a short run.
var placeholderRunsRE = regexp.MustCompile(`(?i)X{8,}|0{10,}`)

// placeholderExactMatches are case-insensitive full-string matches.
// Substring matching for these would over-reject real tokens (a real
// 32-char base64 string containing "test" would be gutted), so the
// match is anchored: only the raw "test", "foo", "dummy" etc. are
// rejected, not tokens that embed them.
var placeholderExactMatches = [][]byte{
	[]byte("dummy"),
	[]byte("test"),
	[]byte("foo"),
	[]byte("bar"),
	[]byte("password"),
	[]byte("changeme"),
}

// placeholderSink sits between dedup and the allowlist in the engine's
// sink chain: it drops any finding whose raw matches IsPlaceholder.
// Living above allowlist is deliberate — placeholders are universal
// noise that every operator wants gone; making the user enumerate them
// in a per-repo allowlist would be a worst-of-both-worlds policy.
//
// Concurrency-safe because scan workers Emit from many goroutines and
// suppCount is incremented from those concurrent calls.
type placeholderSink struct {
	inner     Sink
	mu        sync.Mutex
	suppCount int64
}

// NewPlaceholderFilter wraps inner with placeholder rejection. There's
// no opt-out config knob — placeholder tokens are by definition not
// secrets, and any user who genuinely wants to scan documentation can
// allowlist specific examples instead.
func NewPlaceholderFilter(inner Sink) Sink {
	return &placeholderSink{inner: inner}
}

func (p *placeholderSink) Emit(f Finding) {
	if IsPlaceholder(f.Result.Raw) {
		p.mu.Lock()
		p.suppCount++
		p.mu.Unlock()
		return
	}
	p.inner.Emit(f)
}

func (p *placeholderSink) Close() error { return p.inner.Close() }

// SuppressedCount returns how many findings the placeholder filter
// muted across the scan. Mirrors allowlistSink.SuppressedCount so the
// CLI can surface a "filtered N placeholder(s)" line on stderr the
// same way it does for the allowlist.
func (p *placeholderSink) SuppressedCount() int64 {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.suppCount
}

// PlaceholderSuppressedCounter is the public accessor — callers hold a
// Sink and want the count without knowing the concrete type. Returns
// -1 when sink is not a placeholderSink so future wrapping layers can
// distinguish "no placeholder filter installed" from "zero hits".
func PlaceholderSuppressedCounter(s Sink) int64 {
	if p, ok := s.(*placeholderSink); ok {
		return p.SuppressedCount()
	}
	return -1
}
