// Package authentik detects Authentik identity-provider tokens — long
// alnum strings near the `authentik` keyword. Unverified-by-default;
// the per-tenant host (`<tenant>.goauthentik.io` or self-hosted) isn't
// in the chunk. Verify only fires when an apiBase override is supplied.
package authentik

import (
	"context"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/plenoai/pleno-dlp/pkg/detectors"
)

var apiBase = ""

var httpClient = &http.Client{Timeout: 10 * time.Second}

// tokenRe matches an authentik token key. The key is generated by
// default_token_key -> generate_id(token_length): charset
// string.ascii_letters+string.digits (`[A-Za-z0-9]`) and length
// DEFAULT_TOKEN_LENGTH = 60. token_length is tenant-configurable with
// no documented upper bound, so 60 is treated as a recall-safe minimum
// floor rather than a hard length pin.
// Source: goauthentik/authentik authentik/lib/generators.py (generate_id)
// and authentik/tenants/models.py (DEFAULT_TOKEN_LENGTH = 60).
var tokenRe = regexp.MustCompile(`\b([A-Za-z0-9]{60,})\b`)

// armRe is the assignment-style authentik reference that must appear
// within the radius window — it replaces a bare strings.Contains over
// radius 256, which let any high-entropy 60+ alnum string near the word
// "authentik" match.
var armRe = regexp.MustCompile(`(?i)authentik[_\-]?(api[_\-]?)?(token|key|secret)`)

// minEntropy guards against low-variety 60+ alnum runs. authentik keys
// draw from a 62-char alphabet (~5.95 bits/char ceiling), so a 3.5
// floor culls structured/templated strings without touching real keys.
const minEntropy = 3.5

type Scanner struct{}

func (Scanner) Type() detectors.DetectorType { return detectors.Authentik }

func (Scanner) Keywords() []string { return []string{"authentik"} }

func (s Scanner) FromData(ctx context.Context, verify bool, data []byte) ([]detectors.Result, error) {
	hits := tokenRe.FindAllSubmatchIndex(data, -1)
	if len(hits) == 0 {
		return nil, nil
	}
	lower := strings.ToLower(string(data))
	out := make([]detectors.Result, 0, len(hits))
	seen := map[string]struct{}{}
	for _, h := range hits {
		token := string(data[h[2]:h[3]])
		if _, dup := seen[token]; dup {
			continue
		}
		if !detectors.HasMinEntropy(token, minEntropy) {
			continue
		}
		if !nearKeyword(lower, h[2], h[3]) {
			continue
		}
		seen[token] = struct{}{}
		res := detectors.Result{
			DetectorType: detectors.Authentik,
			Raw:          []byte(token),
			Redacted:     redact(token),
		}
		if verify && apiBase != "" {
			v, err := s.Verify(ctx, token)
			res.Verified = v
			res.VerificationErr = err
		}
		out = append(out, res)
	}
	if len(out) == 0 {
		return nil, nil
	}
	return out, nil
}

// nearKeyword reports whether an `authentik[_-]?(api[_-]?)?(token|key|secret)`
// assignment anchor appears within radius 64 of the candidate token.
func nearKeyword(lower string, start, end int) bool {
	const radius = 64
	from := start - radius
	if from < 0 {
		from = 0
	}
	to := end + radius
	if to > len(lower) {
		to = len(lower)
	}
	return armRe.MatchString(lower[from:to])
}

func (Scanner) Verify(ctx context.Context, secret string) (bool, error) {
	if apiBase == "" {
		return false, nil
	}
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(apiBase, "/")+"/api/v3/core/users/me/", nil)
	if err != nil {
		return false, err
	}
	req.Header.Set("Authorization", "Bearer "+secret)
	resp, err := httpClient.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusOK {
		return true, nil
	}
	return false, nil
}

func redact(t string) string {
	if len(t) <= 8 {
		return t
	}
	return t[:8] + "..."
}

func init() {
	detectors.Register(Scanner{})
}
