package main

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// corpusReport is one corpus's (synthetic or leaky-repo) full result:
// machine-readable (json.Marshal'd into results.json) and rendered as a
// markdown table (results.md) mirroring docs/comparison.md's own layout
// so a reader can diff the two by eye.
type corpusReport struct {
	Corpus string    `json:"corpus"`
	Tools  []recall  `json:"recall"`
	Rows   []fileRow `json:"files"`
}

// resultsBundle is the full contents of results.json: the per-corpus
// reports plus the run metadata (bench/docsync reads this — see issue
// #299 — to regenerate docs/comparison.md's "Live re-measurement"
// section without re-deriving tool versions or a timestamp
// independently).
type resultsBundle struct {
	GeneratedAt string            `json:"generated_at"` // RFC3339, UTC
	Versions    map[string]string `json:"versions"`     // tool name -> `--version` output
	Corpora     []corpusReport    `json:"corpora"`
}

func renderMarkdown(reports []corpusReport, toolVersions map[string]string) string {
	var b strings.Builder
	b.WriteString("# dlp-bench results\n\n")
	b.WriteString("Generated by `make bench` (bench/harness). Machine-readable form: `bench/results/results.json`.\n\n")

	b.WriteString("## Versions\n\n| Tool | Version |\n|---|---|\n")
	for _, tool := range tools {
		v := toolVersions[tool]
		if v == "" {
			v = "(not run)"
		}
		fmt.Fprintf(&b, "| %s | %s |\n", tool, v)
	}
	b.WriteString("\n")

	for _, r := range reports {
		fmt.Fprintf(&b, "## %s\n\n", r.Corpus)
		b.WriteString("| Tool | Detected | Total | Recall |\n|---|---:|---:|---:|\n")
		for _, rec := range r.Tools {
			pct := 0.0
			if rec.Total > 0 {
				pct = 100 * float64(rec.Hit) / float64(rec.Total)
			}
			fmt.Fprintf(&b, "| %s | %d | %d | %.0f%% |\n", rec.Tool, rec.Hit, rec.Total, pct)
		}
		b.WriteString("\n")

		b.WriteString("Per-file outcome (✓ detected, ✗ missed; **bold** = documented pleno-dlp loss):\n\n")
		b.WriteString("| File |")
		for _, tool := range tools {
			fmt.Fprintf(&b, " %s |", tool)
		}
		b.WriteString("\n|---|")
		for range tools {
			b.WriteString("---|")
		}
		b.WriteString("\n")
		for _, row := range r.Rows {
			name := row.File
			if row.KnownMiss != "" {
				name = "**" + name + "**"
			}
			fmt.Fprintf(&b, "| %s |", name)
			for _, tool := range tools {
				mark := "✗"
				if row.Detected[tool] {
					mark = "✓"
				}
				fmt.Fprintf(&b, " %s |", mark)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")

		var known []string
		for _, row := range r.Rows {
			if row.KnownMiss != "" {
				known = append(known, fmt.Sprintf("- `%s`: %s", row.File, row.KnownMiss))
			}
		}
		if len(known) > 0 {
			b.WriteString("Documented pleno-dlp losses on this corpus:\n\n")
			b.WriteString(strings.Join(known, "\n"))
			b.WriteString("\n\n")
		}
	}
	return b.String()
}

func marshalJSON(reports []corpusReport, versions map[string]string) ([]byte, error) {
	bundle := resultsBundle{
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Versions:    versions,
		Corpora:     reports,
	}
	return json.MarshalIndent(bundle, "", "  ")
}
